defaults:
  - dataset: tabula_muris
  - method: maml

model: FCNet
n_way: ???
n_shot: ???
n_query: ???

mode: train

exp:
  name: ???
  save_freq: 10
  resume: false
  seed: 42
  val_freq: 1

optimizer: SGD  # ZSL: Remember to modify!!
lr: 0.1
optimizer_cls:
  _target_: torch.optim.${optimizer}
  lr: ${lr}
  weight_decay: 0.0005
  momentum: 0.9
  nesterov: True

checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name}_${model}
  test_iter: best_model
  time: latest

wandb:
  project: few-shot learning
  entity: one-punch24
  mode: "online" # Can set to offline, disabled

iter_num: 600
